### PR TITLE
changed source code structure to Cobra-based application structure

### PR DESCRIPTION
**Pull request by amir-shiati**

### CODE REVIEW

**Comment by BaseMax** [comment]
> Run markdownlint '**/*.md' --ignore node_modules
```
CODE_OF_CONDUCT.md:70:81 MD013/line-length Line length [Expected: 80; Actual: 87]
CONTRIBUTING.md:5 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
CONTRIBUTING.md:11 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
CONTRIBUTING.md:17 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
CONTRIBUTING.md:23 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
CONTRIBUTING.md:29 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
CONTRIBUTING.md:35 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
CONTRIBUTING.md:41 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
CONTRIBUTING.md:45:81 MD013/line-length Line length [Expected: 80; Actual: 141]
CONTRIBUTING.md:46:81 MD013/line-length Line length [Expected: 80; Actual: 144]
README.md:20 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
README.md:56:81 MD013/line-length Line length [Expected: 80; Actual: 195]
##[error]Process completed with exit code 1.
```

Please review this. @jbampton 

https://github.com/DonyaOS/PackageManager/actions/runs/232607647

**Comment by BaseMax** [comment]
Thanks Amir, Merged.

**Comment by amir-shiati** [comment]
Thank you!
I will be back to help you guys with whatever i can as soon as i'm done
with this project that i'm doing for a client.

**Review by jbampton — COMMENTED** [review]
Hey @BaseMax the .markdownlint.yml got deleted

**Comment by jbampton** [comment]
And `go.mod` got deleted too

**Pull request merged**
